// Font Awesome configuration - SVG icons instead of web fonts
// This eliminates external CSS/font requests and only bundles icons we use

import { library } from '@fortawesome/fontawesome-svg-core';
import { config } from '@fortawesome/fontawesome-svg-core';

// Prevent Font Awesome from adding CSS automatically (we handle it ourselves)
config.autoAddCss = false;

// Solid icons
import {
  faArrowLeft,
  faArrowRight,
  faArrowUpRightFromSquare,
  faBars,
  faBookBible,
  faBookOpen,
  faBuilding,
  faCalendar,
  faCalendarCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChild,
  faChildReaching,
  faChurch,
  faCirclePlay,
  faCircleQuestion,
  faCity,
  faClock,
  faComments,
  faDiamondTurnRight,
  faDice,
  faDoorOpen,
  faDownload,
  faDroplet,
  faEnvelope,
  faExclamationTriangle,
  faGlobe,
  faGraduationCap,
  faHand,
  faHandHoldingHeart,
  faHandshakeAngle,
  faHandsPraying,
  faHeart,
  faHeartCircleCheck,
  faHome,
  faHouse,
  faLaptop,
  faList,
  faLocationDot,
  faMagnifyingGlassLocation,
  faMapLocationDot,
  faMicrophone,
  faMicrophoneSlash,
  faMugHot,
  faMusic,
  faPause,
  faPeopleGroup,
  faPhone,
  faPlay,
  faPuzzlePiece,
  faRepeat,
  faRoad,
  faRoute,
  faSeedling,
  faShirt,
  faStar,
  faSun,
  faTree,
  faUser,
  faUsers,
  faUtensils,
  faVideoSlash,
  faWheatAwn,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

// Brand icons
import {
  faFacebookF,
  faInstagram,
  faXTwitter,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons';

// Regular icons
import {
  faCalendar as faCalendarRegular,
  faClock as faClockRegular,
} from '@fortawesome/free-regular-svg-icons';

// Add all icons to the library
library.add(
  // Solid
  faArrowLeft,
  faArrowRight,
  faArrowUpRightFromSquare,
  faBars,
  faBookBible,
  faBookOpen,
  faBuilding,
  faCalendar,
  faCalendarCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChild,
  faChildReaching,
  faChurch,
  faCirclePlay,
  faCircleQuestion,
  faCity,
  faClock,
  faComments,
  faDiamondTurnRight,
  faDice,
  faDoorOpen,
  faDownload,
  faDroplet,
  faEnvelope,
  faExclamationTriangle,
  faGlobe,
  faGraduationCap,
  faHand,
  faHandHoldingHeart,
  faHandshakeAngle,
  faHandsPraying,
  faHeart,
  faHeartCircleCheck,
  faHome,
  faHouse,
  faLaptop,
  faList,
  faLocationDot,
  faMagnifyingGlassLocation,
  faMapLocationDot,
  faMicrophone,
  faMicrophoneSlash,
  faMugHot,
  faMusic,
  faPause,
  faPeopleGroup,
  faPhone,
  faPlay,
  faPuzzlePiece,
  faRepeat,
  faRoad,
  faRoute,
  faSeedling,
  faShirt,
  faStar,
  faSun,
  faTree,
  faUser,
  faUsers,
  faUtensils,
  faVideoSlash,
  faWheatAwn,
  faXmark,
  // Brands
  faFacebookF,
  faInstagram,
  faXTwitter,
  faYoutube,
  // Regular
  faCalendarRegular,
  faClockRegular,
);

export { library };

